---
title: "Week 2 - Starting a Project and Reading in Data"
author: "Tucker Keuter"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

## Kickoff Activity
- Open the file `bigData.csv` with the tool of your choice
    - What tool did you use?
    - How long does it take to open?
    - How many rows does it have?
    
- Run `install.packages('tidyverse')` in R

## Starting a Project
- An R project simply a folder where all scripts, data, and other content related to your project will exist
- Using the command `getwd()` aka "get working directory" will tell you which folder or project you are in
- Think of projects like rooms in a house and all your project content is stuff in that room
    - If you ask for your water bottle and there is one in the room you are in, that is likely the water bottle you are talking about even if there is a water bottle in a different room
- You can also reference other folders inside of your room, i.e. (In my house, in the living room, in the bottom right desk drawer there is a piece of paper I need)
    - `home/livingRoom/desk/bottomRightDrawer/paper.txt`
    
## Starting a Project
- We are going to start a new project for this class
- File -> New Project
- New/Existing Directory
- Name
- Location
- Create a new script called `readingInData.R`

## Reading In Data
- There are several ways to get data into R
    - Read in a `.csv` file
        - `read.csv('bigData.csv')` (base)
        - `read_csv('bigData.csv')` (tidyverse)
    - Read in a `.xlsx` file (readxl)
        - `read_xlsx('bigData.xlsx')` (tidyverse)
    - Read in a `.rds` file (base)
        - `readRDS('bigData.rds')` (base)
    - Connect to a database (odbc, rdbc, etc) - Out of Scope

- On read in, you should assign a name to the data you are reading in
    - `data = read.csv('bigData.csv')`
    
## Reading in Data
- Move the `bigData.csv` file into your working directory
- Read `bigData.csv` into R
    - Look at the head and tail of your data
    - How many rows does it have?
    - What is the largest value in your data?
    - What is the smallest value in your data?
    - What is the mean of your data?
    - What is the median of your data?
    
## Writing Data
- Data is commonly written from R in either `.csv` or `.rds` format
- All the functions for reading in data above have analogues for writing data
    - `write.csv('bigData.csv)`
    - `saveRDS('bigData.rds)`
    
## Writing Data
- Add 10 to every value in `'bigData.csv'`
- Write this new data to a file called `'bigDataNew.csv'`


## Application
- Go find some data that you have been using recently or use frequently
- Read it into R
- Make a change to it
- Write it out with a new name







